# Generated by Django 5.2.14 on 2026-05-25 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "nostr_pubkey",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "lightning_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("encrypted_nwc_uri", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "merchant",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "nostr_pubkey",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "lightning_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customers",
                        to="merchants.merchant",
                    ),
                ),
            ],
            options={
                "db_table": "customer",
                "ordering": ["created_at", "id"],
                "indexes": [models.Index(fields=["merchant"], name="ix_customer_merchant_id")],
            },
        ),
    ]
