# Generated by Django 5.2.14 on 2026-05-25 17:34

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="ix_customer_email"),
        ),
        migrations.AddIndex(
            model_name="merchant",
            index=models.Index(fields=["name"], name="ix_merchant_name"),
        ),
        migrations.AddIndex(
            model_name="merchant",
            index=models.Index(fields=["lightning_address"], name="ix_merchant_lightning_addr"),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                models.F("merchant"),
                django.db.models.functions.text.Lower("email"),
                name="uq_customer_merchant_email_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("lightning_address__isnull", False),
                    models.Q(("lightning_address", ""), _negated=True),
                ),
                fields=("merchant", "lightning_address"),
                name="uq_customer_merchant_lightning",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("nostr_pubkey__isnull", False),
                    models.Q(("nostr_pubkey", ""), _negated=True),
                ),
                fields=("merchant", "nostr_pubkey"),
                name="uq_customer_merchant_nostr",
            ),
        ),
        migrations.AddConstraint(
            model_name="merchant",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("lightning_address__isnull", False),
                    models.Q(("lightning_address", ""), _negated=True),
                ),
                fields=("lightning_address",),
                name="uq_merchant_lightning_address",
            ),
        ),
        migrations.AddConstraint(
            model_name="merchant",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("nostr_pubkey__isnull", False),
                    models.Q(("nostr_pubkey", ""), _negated=True),
                ),
                fields=("nostr_pubkey",),
                name="uq_merchant_nostr_pubkey",
            ),
        ),
    ]
