# Generated by Django 5.2.14 on 2026-05-25 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("merchants", "0001_initial"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RewardReceipt",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCRUING", "Accruing"),
                            ("PAUSED", "Paused"),
                            ("READY_FOR_PAYOUT", "Ready for payout"),
                            ("PAID", "Paid"),
                        ],
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                (
                    "signed_reward_receipt_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "high_water_mark_value_usd",
                    models.DecimalField(decimal_places=8, max_digits=18),
                ),
                (
                    "merchant_coverage_ratio",
                    models.DecimalField(decimal_places=8, max_digits=18),
                ),
                ("accrual_paused", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reward_receipts",
                        to="merchants.customer",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reward_receipts",
                        to="merchants.merchant",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reward_receipt",
                        to="transactions.btctransaction",
                    ),
                ),
            ],
            options={
                "db_table": "reward_receipt",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RewardCalculation",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("eligible_btc_notional_sats", models.BigIntegerField()),
                (
                    "basis_value_usd",
                    models.DecimalField(decimal_places=8, max_digits=18),
                ),
                (
                    "current_value_usd",
                    models.DecimalField(decimal_places=8, max_digits=18),
                ),
                (
                    "incremental_appreciation_usd",
                    models.DecimalField(decimal_places=8, max_digits=18),
                ),
                (
                    "customer_reward_usd",
                    models.DecimalField(decimal_places=8, max_digits=18),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "reward_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calculations",
                        to="receipts.rewardreceipt",
                    ),
                ),
            ],
            options={
                "db_table": "reward_calculation",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="rewardreceipt",
            index=models.Index(fields=["merchant"], name="ix_reward_receipt_merchant_id"),
        ),
        migrations.AddIndex(
            model_name="rewardreceipt",
            index=models.Index(fields=["customer"], name="ix_reward_receipt_customer_id"),
        ),
        migrations.AddConstraint(
            model_name="rewardreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(("high_water_mark_value_usd__gte", 0)),
                name="ck_reward_receipt_high_water_mark_value_usd",
            ),
        ),
        migrations.AddConstraint(
            model_name="rewardreceipt",
            constraint=models.CheckConstraint(
                condition=models.Q(("merchant_coverage_ratio__gte", 0)),
                name="ck_reward_receipt_merchant_coverage_ratio",
            ),
        ),
        migrations.AddIndex(
            model_name="rewardcalculation",
            index=models.Index(fields=["reward_receipt"], name="ix_reward_calc_receipt_id"),
        ),
        migrations.AddConstraint(
            model_name="rewardcalculation",
            constraint=models.CheckConstraint(
                condition=models.Q(("eligible_btc_notional_sats__gte", 0)),
                name="ck_reward_calculation_eligible_btc_notional_sats",
            ),
        ),
        migrations.AddConstraint(
            model_name="rewardcalculation",
            constraint=models.CheckConstraint(
                condition=models.Q(("basis_value_usd__gte", 0)),
                name="ck_reward_calculation_basis_value_usd",
            ),
        ),
        migrations.AddConstraint(
            model_name="rewardcalculation",
            constraint=models.CheckConstraint(
                condition=models.Q(("current_value_usd__gte", 0)),
                name="ck_reward_calculation_current_value_usd",
            ),
        ),
        migrations.AddConstraint(
            model_name="rewardcalculation",
            constraint=models.CheckConstraint(
                condition=models.Q(("incremental_appreciation_usd__gte", 0)),
                name="ck_reward_calculation_incremental_appreciation_usd",
            ),
        ),
        migrations.AddConstraint(
            model_name="rewardcalculation",
            constraint=models.CheckConstraint(
                condition=models.Q(("customer_reward_usd__gte", 0)),
                name="ck_reward_calculation_customer_reward_usd",
            ),
        ),
    ]
