# Generated by Django 5.2.14 on 2026-05-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "merchants",
            "0002_customer_ix_customer_email_merchant_ix_merchant_name_and_more",
        ),
        ("receipts", "0001_initial"),
        ("transactions", "0002_alter_ingestionrequest_status_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="rewardcalculation",
            index=models.Index(
                fields=["reward_receipt", "-created_at", "-id"],
                name="ix_reward_calc_latest",
            ),
        ),
        migrations.AddIndex(
            model_name="rewardreceipt",
            index=models.Index(
                fields=["merchant", "status", "-created_at", "-id"],
                name="ix_reward_receipt_ops",
            ),
        ),
    ]
