# Generated by Django 5.2.14 on 2026-05-25 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("merchants", "0001_initial"),
        ("rewards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BtcTransaction",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("sats_spent", models.BigIntegerField()),
                (
                    "btc_usd_price_at_purchase",
                    models.DecimalField(decimal_places=8, max_digits=18),
                ),
                (
                    "payment_external_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="btc_transactions",
                        to="merchants.customer",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="btc_transactions",
                        to="merchants.merchant",
                    ),
                ),
                (
                    "reward_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="btc_transactions",
                        to="rewards.rewardpolicy",
                    ),
                ),
            ],
            options={
                "db_table": "btc_transaction",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="IngestionRequest",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("request_hash", models.CharField(blank=True, max_length=128)),
                ("response_payload", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("COMPLETED", "Completed"), ("FAILED", "Failed")],
                        default="COMPLETED",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingestion_requests",
                        to="transactions.btctransaction",
                    ),
                ),
            ],
            options={
                "db_table": "ingestion_request",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="btctransaction",
            index=models.Index(fields=["merchant"], name="ix_btc_transaction_merchant_id"),
        ),
        migrations.AddIndex(
            model_name="btctransaction",
            index=models.Index(fields=["customer"], name="ix_btc_transaction_customer_id"),
        ),
        migrations.AddIndex(
            model_name="btctransaction",
            index=models.Index(fields=["reward_policy"], name="ix_btc_tx_reward_policy_id"),
        ),
        migrations.AddConstraint(
            model_name="btctransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("sats_spent__gt", 0)),
                name="ck_btc_transaction_sats_spent",
            ),
        ),
        migrations.AddConstraint(
            model_name="btctransaction",
            constraint=models.CheckConstraint(
                condition=models.Q(("btc_usd_price_at_purchase__gt", 0)),
                name="ck_btc_transaction_btc_usd_price_at_purchase",
            ),
        ),
        migrations.AddIndex(
            model_name="ingestionrequest",
            index=models.Index(fields=["transaction"], name="ix_ingestion_req_tx_id"),
        ),
    ]
