# Generated by Django 5.2.14 on 2026-05-25 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "merchants",
            "0002_customer_ix_customer_email_merchant_ix_merchant_name_and_more",
        ),
        ("rewards", "0002_rewardpolicy_ix_reward_policy_current_and_more"),
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingestionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="COMPLETED",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="ingestionrequest",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ingestion_requests",
                to="transactions.btctransaction",
            ),
        ),
        migrations.AddIndex(
            model_name="btctransaction",
            index=models.Index(
                fields=["merchant", "-created_at", "-id"],
                name="ix_btc_tx_merchant_recent",
            ),
        ),
        migrations.AddIndex(
            model_name="ingestionrequest",
            index=models.Index(fields=["status", "-created_at", "-id"], name="ix_ingestion_req_status"),
        ),
        migrations.AddConstraint(
            model_name="btctransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("payment_external_id__isnull", False),
                    models.Q(("payment_external_id", ""), _negated=True),
                ),
                fields=("payment_external_id",),
                name="uq_btc_transaction_payment_external_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestionrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "COMPLETED"), _negated=True),
                    ("transaction__isnull", False),
                    _connector="OR",
                ),
                name="ck_ingestion_completed_has_tx",
            ),
        ),
    ]
