# Generated by Django 5.2.14 on 2026-05-25 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RewardPolicy",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("merchant_retention_bps", models.PositiveIntegerField()),
                ("customer_share_bps", models.PositiveIntegerField()),
                (
                    "min_coverage_ratio",
                    models.DecimalField(decimal_places=4, max_digits=8),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="ACTIVE",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reward_policies",
                        to="merchants.merchant",
                    ),
                ),
            ],
            options={
                "db_table": "reward_policy",
                "ordering": ["-created_at", "-id"],
                "indexes": [models.Index(fields=["merchant"], name="ix_reward_policy_merchant_id")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("merchant_retention_bps__gte", 0),
                            ("merchant_retention_bps__lte", 10000),
                        ),
                        name="ck_reward_policy_merchant_retention_bps",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("customer_share_bps__gte", 0),
                            ("customer_share_bps__lte", 10000),
                        ),
                        name="ck_reward_policy_customer_share_bps",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("min_coverage_ratio__gt", 0)),
                        name="ck_reward_policy_min_coverage_ratio",
                    ),
                ],
            },
        ),
    ]
