# Generated by Django 5.2.14 on 2026-05-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "merchants",
            "0002_customer_ix_customer_email_merchant_ix_merchant_name_and_more",
        ),
        ("rewards", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="rewardpolicy",
            index=models.Index(
                fields=["merchant", "status", "-created_at", "-id"],
                name="ix_reward_policy_current",
            ),
        ),
        migrations.AddConstraint(
            model_name="rewardpolicy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("merchant",),
                name="uq_reward_policy_one_active_per_merchant",
            ),
        ),
    ]
