# Generated by Django 5.2.14 on 2026-05-25 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreasuryWallet",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=32,
                    ),
                ),
                ("btc_balance", models.DecimalField(decimal_places=8, max_digits=28)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="treasury_wallets",
                        to="merchants.merchant",
                    ),
                ),
            ],
            options={
                "db_table": "treasury_wallet",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TreasurySnapshot",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("btc_usd_price", models.DecimalField(decimal_places=8, max_digits=18)),
                (
                    "allocated_usd_value",
                    models.DecimalField(decimal_places=8, max_digits=18),
                ),
                (
                    "coverage_ratio",
                    models.DecimalField(decimal_places=8, max_digits=18),
                ),
                ("snapshot_source", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "treasury_wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots",
                        to="treasury.treasurywallet",
                    ),
                ),
            ],
            options={
                "db_table": "treasury_snapshot",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PayoutBatch",
            fields=[
                (
                    "id",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("QUEUED", "Queued"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="DRAFT",
                        max_length=32,
                    ),
                ),
                ("total_usd", models.DecimalField(decimal_places=8, max_digits=18)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payout_batches",
                        to="merchants.merchant",
                    ),
                ),
            ],
            options={
                "db_table": "payout_batch",
                "ordering": ["-created_at", "-id"],
                "indexes": [models.Index(fields=["merchant"], name="ix_payout_batch_merchant_id")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("total_usd__gte", 0)),
                        name="ck_payout_batch_total_usd",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="treasurywallet",
            index=models.Index(fields=["merchant"], name="ix_treasury_wallet_merchant_id"),
        ),
        migrations.AddConstraint(
            model_name="treasurywallet",
            constraint=models.CheckConstraint(
                condition=models.Q(("btc_balance__gte", 0)),
                name="ck_treasury_wallet_btc_balance",
            ),
        ),
        migrations.AddIndex(
            model_name="treasurysnapshot",
            index=models.Index(fields=["treasury_wallet"], name="ix_treasury_snap_wallet_id"),
        ),
        migrations.AddConstraint(
            model_name="treasurysnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("btc_usd_price__gt", 0)),
                name="ck_treasury_snapshot_btc_usd_price",
            ),
        ),
        migrations.AddConstraint(
            model_name="treasurysnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("allocated_usd_value__gte", 0)),
                name="ck_treasury_snapshot_allocated_usd_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="treasurysnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("coverage_ratio__gte", 0)),
                name="ck_treasury_snapshot_coverage_ratio",
            ),
        ),
    ]
