# Generated by Django 5.2.14 on 2026-05-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "merchants",
            "0002_customer_ix_customer_email_merchant_ix_merchant_name_and_more",
        ),
        ("treasury", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="payoutbatch",
            index=models.Index(
                fields=["merchant", "status", "-created_at", "-id"],
                name="ix_payout_batch_ops",
            ),
        ),
        migrations.AddIndex(
            model_name="treasurysnapshot",
            index=models.Index(
                fields=["treasury_wallet", "-created_at", "-id"],
                name="ix_treasury_snap_latest",
            ),
        ),
        migrations.AddIndex(
            model_name="treasurywallet",
            index=models.Index(
                fields=["merchant", "status", "-created_at", "-id"],
                name="ix_treasury_wallet_ops",
            ),
        ),
        migrations.AddConstraint(
            model_name="treasurywallet",
            constraint=models.UniqueConstraint(fields=("merchant", "label"), name="uq_treasury_wallet_merchant_label"),
        ),
    ]
